"""Tests for hamq.core.wsjtx (WSJT-X UDP protocol).

Golden packets live in tests/fixtures/wsjtx/ and are generated by
scripts/make_wsjtx_fixtures.py; their bytes were cross-checked against Qt's own
QDataStream (see tests/fixtures/wsjtx/README.md). The expected values below are
written out by hand on purpose: they are the specification the fixtures and the
encoder must both match.
"""

from __future__ import annotations

import ast
import os
import random
import struct
import subprocess
import sys
import time
import tracemalloc
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from hamq.core.wsjtx import (
    CLOSE,
    HEARTBEAT,
    LOGGED_ADIF,
    MAGIC,
    QSO_LOGGED,
    STATUS,
    Writer,
    decode,
    encode_close,
    encode_heartbeat,
    encode_logged_adif,
    encode_status,
)

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "tests" / "fixtures" / "wsjtx"
SCRIPT = ROOT / "scripts" / "make_wsjtx_fixtures.py"
MODULE = ROOT / "hamq" / "core" / "wsjtx.py"
UTC = timezone.utc

STATUS_MANDATORY = ["type", "client", "schema", "freq_hz", "mode", "dx_call"]
STATUS_OPTIONAL = [
    "report",
    "tx_mode",
    "tx_enabled",
    "transmitting",
    "decoding",
    "rx_df",
    "tx_df",
    "de_call",
    "de_grid",
    "dx_grid",
    "tx_watchdog",
    "sub_mode",
    "fast_mode",
    "special_op_mode",
    "frequency_tolerance",
    "tr_period",
    "configuration_name",
    "tx_message",
]
# JTDX forked the protocol before WSJT-X 2.0: its Status has the WSJT-X fields up to
# fast_mode, then a bool tx_first, and nothing else (jtdx MessageClient::status_update)
JTDX_STATUS_OPTIONAL = STATUS_OPTIONAL[: STATUS_OPTIONAL.index("fast_mode") + 1] + ["tx_first"]
KEYS = {
    "heartbeat": ["type", "client", "schema", "max_schema", "version", "revision"],
    "close": ["type", "client", "schema"],
    "logged_adif": ["type", "client", "schema", "adif"],
    "other": ["type", "code", "client", "schema"],
}

# --- the fixture scenario: YU1ABC (KN04ft) works YU7ABC (JN95) on 40 m FT8 -----------------

ADIF_HEADER = "\n<adif_ver:5>3.1.0\n<programid:6>WSJT-X\n<EOH>\n"  # MessageClient::logged_ADIF
ADIF_TEXT = (
    ADIF_HEADER + "<call:6>YU7ABC <gridsquare:4>JN95 <mode:3>FT8 <rst_sent:3>-12 <rst_rcvd:3>-09"
    " <qso_date:8>20260915 <time_on:6>184500 <qso_date_off:8>20260915 <time_off:6>184615"
    " <band:3>40m <freq:8>7.075234 <station_callsign:6>YU1ABC <my_gridsquare:6>KN04ft"
    " <tx_pwr:3>100 <comment:25>FT8  Sent: -12  Rcvd: -09 <name:5>Đorđe <EOR>"
)
LATIN1_ADIF_TEXT = (
    ADIF_HEADER + "<call:6>DL1ABC <gridsquare:4>JO62 <mode:3>FT8 <rst_sent:3>-15 <rst_rcvd:3>-07"
    " <qso_date:8>20260916 <time_on:6>061530 <qso_date_off:8>20260916 <time_off:6>061645"
    " <band:3>20m <freq:9>14.075512 <station_callsign:6>YU1ABC <my_gridsquare:6>KN04ft"
    " <tx_pwr:3>100 <name:6>Jürgen <EOR>"
)

STATUS_FT8 = {
    "type": "status",
    "client": "WSJT-X",
    "schema": 2,
    "freq_hz": 7074000,
    "mode": "FT8",
    "dx_call": "YU7ABC",
    "report": "-12",
    "tx_mode": "FT8",
    "tx_enabled": True,
    "transmitting": False,
    "decoding": False,
    "rx_df": 1234,
    "tx_df": 1234,
    "de_call": "YU1ABC",
    "de_grid": "KN04ft",
    "dx_grid": "JN95",
    "tx_watchdog": False,
    "sub_mode": None,  # WSJT-X sends a null QString when the mode has no submode
    "fast_mode": False,
    "special_op_mode": 0,
    "frequency_tolerance": 0xFFFFFFFF,  # not applicable to FT8
    "tr_period": 0xFFFFFFFF,
    "configuration_name": "Default",
    "tx_message": "YU7ABC YU1ABC -12",
}
STATUS_FT8_KWARGS = {key: STATUS_FT8[key] for key in STATUS_OPTIONAL}

STATUS_JTDX = {  # JTDX 2.2.159 on 20 m, Tx enabled in the first (even) period
    "type": "status",
    "client": "JTDX",
    "schema": 2,
    "freq_hz": 14074000,
    "mode": "FT8",
    "dx_call": "DL1ABC",
    "report": "-10",
    "tx_mode": "FT8",
    "tx_enabled": True,
    "transmitting": False,
    "decoding": False,
    "rx_df": 1500,
    "tx_df": 1210,
    "de_call": "YU1ABC",
    "de_grid": "KN04ft",
    "dx_grid": "JO62",
    "tx_watchdog": False,
    "sub_mode": None,  # JTDX always sends a null QString here
    "fast_mode": False,  # always false in JTDX
    "tx_first": True,
}
STATUS_JTDX_KWARGS = {key: STATUS_JTDX[key] for key in JTDX_STATUS_OPTIONAL}

EXPECTED = {
    "heartbeat_schema2.bin": {
        "type": "heartbeat",
        "client": "WSJT-X",
        "schema": 2,
        "max_schema": 3,
        "version": "2.7.0",
        "revision": "",
    },
    "heartbeat_schema3.bin": {
        "type": "heartbeat",
        "client": "WSJT-X",
        "schema": 3,
        "max_schema": 3,
        "version": "2.7.0",
        "revision": "a1b2c3d",
    },
    "heartbeat_jtdx.bin": {
        "type": "heartbeat",
        "client": "JTDX",
        "schema": 2,
        "max_schema": 3,
        "version": "2.2.159",
        "revision": None,  # JTDX does not send the revision field
    },
    "status_ft8.bin": STATUS_FT8,
    "truncated_status.bin": {
        key: STATUS_FT8[key] for key in STATUS_MANDATORY + STATUS_OPTIONAL[:7]
    },  # cut inside de_call: whole fields before it are kept
    "status_jtdx.bin": STATUS_JTDX,
    "close.bin": {"type": "close", "client": "WSJT-X", "schema": 2},
    "logged_adif.bin": {
        "type": "logged_adif",
        "client": "WSJT-X",
        "schema": 2,
        "adif": ADIF_TEXT,
    },
    "logged_adif_latin1.bin": {
        "type": "logged_adif",
        "client": "WSJT-X",
        "schema": 2,
        "adif": LATIN1_ADIF_TEXT,
    },
    "qso_logged.bin": {"type": "other", "code": 5, "client": "WSJT-X", "schema": 2},
    "bad_magic.bin": None,
}


def fixture(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


def qso_logged_packet() -> bytes:
    """QSO Logged (type 5) as MessageClient::qso_logged writes it."""
    return (
        Writer()
        .header(QSO_LOGGED, "WSJT-X", 2)
        .qdatetime(datetime(2026, 9, 15, 18, 46, 15, tzinfo=UTC))  # time off
        .utf8("YU7ABC")
        .utf8("JN95")
        .u64(7075234)  # dial + Tx audio offset
        .utf8("FT8")
        .utf8("-12")
        .utf8("-09")
        .utf8("100")
        .utf8("FT8  Sent: -12  Rcvd: -09")
        .utf8("Đorđe")
        .qdatetime(datetime(2026, 9, 15, 18, 45, 0, tzinfo=UTC))  # time on
        .utf8("")  # operator
        .utf8("YU1ABC")
        .utf8("KN04ft")
        .utf8("")  # exchange sent
        .utf8("")  # exchange received
        .utf8("")  # propagation mode
        .getvalue()
    )


def jtdx_status_packet(client: str = "JTDX", tx_first: bool = True) -> bytes:
    """Status as JTDX's MessageClient::status_update writes it, statement by statement."""
    return (
        Writer()
        .header(STATUS, client, 2)
        .u64(14074000)  # Frequency = quint64
        .utf8("FT8")
        .utf8("DL1ABC")
        .utf8("-10")  # report
        .utf8("FT8")  # Tx mode
        .boolean(True)  # Tx enabled
        .boolean(False)  # transmitting
        .boolean(False)  # decoding
        .i32(1500)  # Rx DF: qint32 in JTDX, quint32 in WSJT-X
        .i32(1210)  # Tx DF
        .utf8("YU1ABC")
        .utf8("KN04ft")
        .utf8("JO62")
        .boolean(False)  # Tx watchdog
        .utf8(None)  # sub-mode: QString {}
        .boolean(False)  # fast mode
        .boolean(tx_first)
        .getvalue()
    )


ENCODED = {
    "heartbeat_schema2.bin": lambda: encode_heartbeat("WSJT-X"),
    "heartbeat_schema3.bin": lambda: encode_heartbeat("WSJT-X", revision="a1b2c3d", schema=3),
    "heartbeat_jtdx.bin": lambda: (
        Writer().header(HEARTBEAT, "JTDX", 2).u32(3).utf8("2.2.159").getvalue()
    ),
    "status_ft8.bin": lambda: encode_status(
        "WSJT-X", 7074000, "FT8", "YU7ABC", **STATUS_FT8_KWARGS
    ),
    "status_jtdx.bin": lambda: encode_status(
        "JTDX", 14074000, "FT8", "DL1ABC", **STATUS_JTDX_KWARGS
    ),
    "close.bin": lambda: encode_close("WSJT-X"),
    "logged_adif.bin": lambda: encode_logged_adif("WSJT-X", ADIF_TEXT),
    "logged_adif_latin1.bin": lambda: encode_logged_adif("WSJT-X", LATIN1_ADIF_TEXT, latin1=True),
    "qso_logged.bin": qso_logged_packet,
}

# --- datagrams captured from a real WSJT-X 2.7.0 (see captured/README.md) ---------------------

CAPTURED_STATUS = {  # first Status after start: no rig yet, null DX call, grid and message
    "type": "status",
    "client": "WSJT-X",
    "schema": 2,
    "freq_hz": 0,
    "mode": "FT8",
    "dx_call": None,
    "report": "-15",
    "tx_mode": "FT8",
    "tx_enabled": False,
    "transmitting": False,
    "decoding": False,
    "rx_df": 1500,
    "tx_df": 1500,
    "de_call": "YU1ABC",
    "de_grid": "KN04ft",
    "dx_grid": None,
    "tx_watchdog": False,
    "sub_mode": None,
    "fast_mode": False,
    "special_op_mode": 0,
    "frequency_tolerance": 0xFFFFFFFF,
    "tr_period": 0xFFFFFFFF,
    "configuration_name": "Default",
    "tx_message": None,
}
CAPTURED_ADIF = (
    "\n<adif_ver:5>3.1.0\n<programid:6>WSJT-X\n<EOH>\n<call:6>YU7ABC <gridsquare:4>JN95"
    " <mode:3>FT8 <rst_sent:0> <rst_rcvd:0> <qso_date:8>20260929 <time_on:6>183140"
    " <qso_date_off:8>20260929 <time_off:6>183140 <band:3>20m <freq:9>14.075500"
    " <station_callsign:6>YU1ABC <my_gridsquare:6>KN04ft <comment:15>?or?e 73 Jürgen <EOR>"
)
CAPTURED_EXPECTED = {
    "captured/wsjtx-2.7.0_heartbeat.bin": EXPECTED["heartbeat_schema2.bin"],
    "captured/wsjtx-2.7.0_heartbeat_schema3.bin": dict(EXPECTED["heartbeat_schema2.bin"], schema=3),
    "captured/wsjtx-2.7.0_status_startup.bin": CAPTURED_STATUS,
    "captured/wsjtx-2.7.0_status.bin": dict(
        CAPTURED_STATUS, freq_hz=14074000, dx_call="YU7ABC", dx_grid="JN95"
    ),
    "captured/wsjtx-2.7.0_status_schema3.bin": dict(
        CAPTURED_STATUS, schema=3, freq_hz=14074000, dx_call="DL1ABC", dx_grid="JO62"
    ),
    "captured/wsjtx-2.7.0_qso_logged.bin": {
        "type": "other",
        "code": 5,
        "client": "WSJT-X",
        "schema": 2,
    },
    "captured/wsjtx-2.7.0_logged_adif.bin": {
        "type": "logged_adif",
        "client": "WSJT-X",
        "schema": 2,
        "adif": CAPTURED_ADIF,
    },
    "captured/wsjtx-2.7.0_close_schema3.bin": {"type": "close", "client": "WSJT-X", "schema": 3},
}
ALL_EXPECTED = dict(EXPECTED, **CAPTURED_EXPECTED)


def captured_qso_logged_packet() -> bytes:
    """The captured QSO Logged message, rebuilt field by field."""
    logged = datetime(2026, 9, 29, 18, 31, 40, 12000, tzinfo=UTC)  # Julian day 2461313
    return (
        Writer()
        .header(QSO_LOGGED, "WSJT-X", 2)
        .qdatetime(logged)  # time off
        .utf8("YU7ABC")
        .utf8("JN95")
        .u64(14075500)
        .utf8("FT8")
        .utf8("")  # report sent
        .utf8("")  # report received
        .utf8("")  # Tx power
        .utf8("Đorđe 73 Jürgen")  # comments: UTF-8 here, unlike the ADIF record
        .utf8("")  # name
        .qdatetime(logged)  # time on
        .utf8("")  # operator
        .utf8("YU1ABC")
        .utf8("KN04ft")
        .utf8("")  # exchange sent
        .utf8("")  # exchange received
        .utf8(None)  # propagation mode: null
        .getvalue()
    )


def reencode_captured(name: str) -> bytes:
    """Build a captured packet again from its decoded values with the hamq encoder."""
    msg = CAPTURED_EXPECTED[name]
    client, schema = msg["client"], msg["schema"]
    if msg["type"] == "heartbeat":
        return encode_heartbeat(client, msg["max_schema"], msg["version"], msg["revision"], schema)
    if msg["type"] == "status":
        optional = {key: msg[key] for key in STATUS_OPTIONAL}
        return encode_status(
            client, msg["freq_hz"], msg["mode"], msg["dx_call"], schema=schema, **optional
        )
    if msg["type"] == "logged_adif":
        return encode_logged_adif(client, msg["adif"], schema, latin1=True)  # as WSJT-X does
    if msg["type"] == "close":
        return encode_close(client, schema)
    return captured_qso_logged_packet()


def status_wire_order(client: str | None) -> list[str]:
    """The optional Status keys in wire order: JTDX (id "JTDX" or "JTDX - <rig>") has its own."""
    if client is not None and client.startswith("JTDX"):
        return JTDX_STATUS_OPTIONAL
    return STATUS_OPTIONAL


def check_message(msg: object) -> None:
    """Shape every decode() result must have (used by the fuzz tests)."""
    if msg is None:
        return
    assert isinstance(msg, dict)
    assert msg["schema"] in (2, 3)
    assert msg["client"] is None or isinstance(msg["client"], str)
    keys = list(msg)
    if msg["type"] == "status":
        assert keys[:6] == STATUS_MANDATORY
        optional = status_wire_order(msg["client"])
        assert keys[6:] == optional[: len(keys) - 6]  # a prefix, in wire order
        assert isinstance(msg["freq_hz"], int)
    else:
        assert keys == KEYS[msg["type"]]


# --- constants and the Writer primitives ----------------------------------------------------


def test_constants_match_network_message_hpp():
    assert MAGIC == 0xADBCCBDA
    assert (HEARTBEAT, STATUS, QSO_LOGGED, CLOSE, LOGGED_ADIF) == (0, 1, 5, 6, 12)


@pytest.mark.parametrize(
    ("method", "value", "expected"),
    [
        ("u8", 7, "07"),
        ("u8", 255, "ff"),
        ("boolean", True, "01"),
        ("boolean", False, "00"),
        ("u32", MAGIC, "adbccbda"),
        ("i32", -1, "ffffffff"),
        ("i32", 1234, "000004d2"),
        ("u64", 7074000, "00000000006bf0d0"),
        ("u64", 2**64 - 1, "ffffffffffffffff"),
        ("i64", -2, "fffffffffffffffe"),
        ("double", 1.5, "3ff8000000000000"),
        ("double", -0.25, "bfd0000000000000"),
        ("byte_array", None, "ffffffff"),
        ("byte_array", b"", "00000000"),
        ("byte_array", b"ab", "000000026162"),
        ("utf8", None, "ffffffff"),
        ("utf8", "", "00000000"),
        ("utf8", "FT8", "00000003465438"),
        ("utf8", "Đorđe", "00000007c4906f72c49165"),  # length counts UTF-8 bytes
        ("latin1", "Jürgen", "000000064afc7267656e"),  # QString::toLatin1()
        ("latin1", "Đorđe", "000000053f6f723f65"),  # letters outside Latin-1 become '?'
        ("latin1", None, "ffffffff"),
    ],
)
def test_writer_primitives(method, value, expected):
    assert getattr(Writer(), method)(value).getvalue() == bytes.fromhex(expected)


def test_writer_qdatetime_matches_qt():
    # Qt 6.10 QDataStream (Qt_5_2 and Qt_5_4) writes this for
    # QDateTime(QDate(2026, 9, 15), QTime(18, 46, 15), Qt::UTC): Julian day 2461299,
    # 67 575 000 ms since midnight, time spec 1 (UTC).
    expected = bytes.fromhex("000000000025 8e73 04071cd8 01")
    assert Writer().qdatetime(datetime(2026, 9, 15, 18, 46, 15, tzinfo=UTC)).getvalue() == expected
    belgrade = timezone(timedelta(hours=2))
    local = datetime(2026, 9, 15, 20, 46, 15, tzinfo=belgrade)
    assert Writer().qdatetime(local).getvalue() == expected  # converted to UTC first
    millis = Writer().qdatetime(datetime(2026, 9, 15, 0, 0, 0, 999999, tzinfo=UTC)).getvalue()
    assert millis[8:12] == (999).to_bytes(4, "big")


def test_writer_header_and_chaining():
    writer = Writer()
    assert writer.header(STATUS, "WSJT-X", 3) is writer
    assert writer.getvalue() == bytes.fromhex("adbccbda 00000003 00000001 00000006") + b"WSJT-X"
    assert Writer().getvalue() == b""


@pytest.mark.parametrize(
    ("method", "value"),
    [
        ("u8", 256),
        ("u8", -1),
        ("u32", -1),
        ("u32", 2**32),
        ("i32", 2**31),
        ("u64", -1),
        ("u64", 2**64),
        ("i64", 2**63),
        ("qdatetime", datetime(2026, 9, 15, 18, 46, 15)),  # naive
    ],
)
def test_writer_rejects_out_of_range_values(method, value):
    with pytest.raises(ValueError):
        getattr(Writer(), method)(value)


@pytest.mark.parametrize(
    ("method", "value"),
    [
        ("u32", 1.5),
        ("u64", "7074000"),
        ("u8", None),
        ("boolean", "False"),  # a non-empty string is truthy: must not become true
        ("boolean", None),
        ("boolean", 1),
        ("double", "1.5"),
        ("utf8", 5),
        ("utf8", b"FT8"),
        ("latin1", 5),
        ("byte_array", "FT8"),
        ("byte_array", 5),
    ],
)
def test_writer_rejects_wrong_types(method, value):
    with pytest.raises(TypeError):
        getattr(Writer(), method)(value)


def test_writer_qdatetime_rejects_dates():
    with pytest.raises(TypeError):
        Writer().qdatetime(datetime(2026, 9, 15, tzinfo=UTC).date())


# --- wire layout of the encoders --------------------------------------------------------------


def test_heartbeat_wire_layout():
    expected = (
        bytes.fromhex("adbccbda 00000002 00000000 00000006")
        + b"WSJT-X"
        + bytes.fromhex("00000003 00000005")
        + b"2.7.0"
        + bytes.fromhex("00000000")  # revision: empty string
    )
    assert encode_heartbeat("WSJT-X") == expected


def test_status_mandatory_wire_layout():
    expected = (
        bytes.fromhex("adbccbda 00000002 00000001 00000006")
        + b"WSJT-X"
        + bytes.fromhex("00000000006bf0d0 00000003")
        + b"FT8"
        + bytes.fromhex("00000006")
        + b"YU7ABC"
    )
    assert encode_status("WSJT-X", 7074000, "FT8", "YU7ABC") == expected


def test_close_and_logged_adif_wire_layout():
    header = bytes.fromhex("adbccbda 00000003 00000006 00000006") + b"WSJT-X"
    assert encode_close("WSJT-X", schema=3) == header
    adif = "<call:6>YU7ABC <EOR>"
    assert encode_logged_adif("WSJT-X", adif) == (
        bytes.fromhex("adbccbda 00000002 0000000c 00000006")
        + b"WSJT-X"
        + len(adif).to_bytes(4, "big")
        + adif.encode()
    )


def test_encode_status_writes_fields_up_to_the_last_one_given():
    msg = decode(encode_status("WSJT-X", 14074000, "FT8", "DL1ABC", decoding=True))
    assert list(msg) == STATUS_MANDATORY + STATUS_OPTIONAL[:5]
    assert msg["report"] == ""
    assert msg["tx_mode"] == ""
    assert msg["tx_enabled"] is False
    assert msg["transmitting"] is False
    assert msg["decoding"] is True

    msg = decode(encode_status("WSJT-X", 14074000, "FT8", tr_period=15))
    assert list(msg) == STATUS_MANDATORY + STATUS_OPTIONAL[:16]
    assert msg["dx_call"] == ""
    assert msg["rx_df"] == msg["tx_df"] == msg["frequency_tolerance"] == 0xFFFFFFFF
    assert msg["special_op_mode"] == 0
    assert msg["tr_period"] == 15


def test_encode_status_rejects_unknown_fields():
    with pytest.raises(TypeError, match="snr"):
        encode_status("WSJT-X", 14074000, "FT8", snr=-10)


def test_encode_status_rejects_values_of_the_wrong_type():
    with pytest.raises(TypeError):
        encode_status("WSJT-X", 14074000, "FT8", tx_enabled="no")
    with pytest.raises(TypeError):
        encode_status("WSJT-X", 14074000, "FT8", rx_df="1500")


def test_encode_status_picks_the_jtdx_layout_by_client_id():
    msg = decode(encode_status("JTDX - IC7300", 14074000, "FT8", "DL1ABC", tx_first=True))
    assert list(msg) == STATUS_MANDATORY + JTDX_STATUS_OPTIONAL
    assert msg["tx_first"] is True
    assert (msg["sub_mode"], msg["fast_mode"]) == ("", False)  # defaults before tx_first
    msg = decode(encode_status("JTDX", 14074000, "FT8", "DL1ABC", de_grid="KN04ft"))
    assert list(msg) == STATUS_MANDATORY + JTDX_STATUS_OPTIONAL[:9]
    # JTDX has no special_op_mode (and nothing after tx_first); WSJT-X has no tx_first
    for field in ("special_op_mode", "frequency_tolerance", "tx_message"):
        with pytest.raises(TypeError, match=field):
            encode_status("JTDX", 14074000, "FT8", **{field: STATUS_FT8[field]})
    for client in ("WSJT-X", "MSHV", None):
        with pytest.raises(TypeError, match="tx_first"):
            encode_status(client, 14074000, "FT8", tx_first=True)


@pytest.mark.parametrize("schema", [0, 1, 4])
def test_encoders_reject_unsupported_schemas(schema):
    with pytest.raises(ValueError):
        encode_heartbeat("WSJT-X", schema=schema)
    with pytest.raises(ValueError):
        encode_status("WSJT-X", 14074000, "FT8", schema=schema)
    with pytest.raises(ValueError):
        encode_close("WSJT-X", schema=schema)
    with pytest.raises(ValueError):
        encode_logged_adif("WSJT-X", "<EOR>", schema=schema)


# --- golden fixtures ---------------------------------------------------------------------------


def test_fixture_directory_has_every_expected_packet():
    assert sorted(p.name for p in FIXTURES.glob("*.bin")) == sorted(EXPECTED)


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_fixture_decodes_to_expected(name):
    assert decode(fixture(name)) == EXPECTED[name]


@pytest.mark.parametrize("name", sorted(ENCODED))
def test_encoder_reproduces_fixture_byte_for_byte(name):
    assert ENCODED[name]() == fixture(name)


def test_truncated_and_bad_magic_fixtures_derive_from_good_packets():
    status = fixture("status_ft8.bin")
    truncated = fixture("truncated_status.bin")
    assert status.startswith(truncated)
    assert len(truncated) < len(status)
    good = fixture("heartbeat_schema2.bin")
    bad = fixture("bad_magic.bin")
    assert bad[:4] == good[:4][::-1]  # magic written little-endian
    assert bad[4:] == good[4:]


def test_logged_adif_fixture_carries_serbian_name_as_utf8():
    data = fixture("logged_adif.bin")
    assert "Đorđe".encode() in data
    assert decode(data)["adif"].endswith("<name:5>Đorđe <EOR>")


# --- datagrams captured from a real WSJT-X 2.7.0 ----------------------------------------------


def test_captured_directory_has_every_expected_packet():
    names = sorted(f"captured/{p.name}" for p in (FIXTURES / "captured").glob("*.bin"))
    assert names == sorted(CAPTURED_EXPECTED)


@pytest.mark.parametrize("name", sorted(CAPTURED_EXPECTED))
def test_captured_wsjtx_packet_decodes(name):
    assert decode(fixture(name)) == CAPTURED_EXPECTED[name]


@pytest.mark.parametrize("name", sorted(CAPTURED_EXPECTED))
def test_encoder_reproduces_captured_wsjtx_packet(name):
    assert reencode_captured(name) == fixture(name)


def test_real_wsjtx_sends_the_adif_record_in_latin1():
    data = fixture("captured/wsjtx-2.7.0_logged_adif.bin")
    assert b"<comment:15>?or?e 73 J\xfcrgen <EOR>" in data  # Đ and đ lost before sending
    with pytest.raises(UnicodeDecodeError):
        data[26:].decode("utf-8")  # the ADIF text after header and length
    assert decode(data)["adif"].endswith("<comment:15>?or?e 73 Jürgen <EOR>")


def test_synthetic_heartbeat_is_identical_to_the_captured_one():
    assert fixture("heartbeat_schema2.bin") == fixture("captured/wsjtx-2.7.0_heartbeat.bin")


# --- round trips, strings, schemas -------------------------------------------------------------


@pytest.mark.parametrize("schema", [2, 3])
def test_round_trip_every_type(schema):
    assert decode(encode_heartbeat("WSJT-X", 3, "2.7.0", "a1b2c3d", schema=schema)) == {
        "type": "heartbeat",
        "client": "WSJT-X",
        "schema": schema,
        "max_schema": 3,
        "version": "2.7.0",
        "revision": "a1b2c3d",
    }
    assert decode(encode_status("WSJT-X", 14074000, "FT8", "DL1ABC", schema=schema)) == {
        "type": "status",
        "client": "WSJT-X",
        "schema": schema,
        "freq_hz": 14074000,
        "mode": "FT8",
        "dx_call": "DL1ABC",
    }
    full = dict(STATUS_FT8, schema=schema)
    packet = encode_status("WSJT-X", 7074000, "FT8", "YU7ABC", schema=schema, **STATUS_FT8_KWARGS)
    assert decode(packet) == full
    jtdx = dict(STATUS_JTDX, schema=schema)
    packet = encode_status("JTDX", 14074000, "FT8", "DL1ABC", schema=schema, **STATUS_JTDX_KWARGS)
    assert decode(packet) == jtdx
    assert decode(encode_close("JTDX", schema=schema)) == {
        "type": "close",
        "client": "JTDX",
        "schema": schema,
    }
    assert decode(encode_logged_adif("WSJT-X", ADIF_TEXT, schema=schema)) == {
        "type": "logged_adif",
        "client": "WSJT-X",
        "schema": schema,
        "adif": ADIF_TEXT,
    }
    other = Writer().header(7, "WSJT-X", schema).getvalue()  # Replay, no payload
    assert decode(other) == {"type": "other", "code": 7, "client": "WSJT-X", "schema": schema}


def test_round_trip_non_default_status_values():
    values = {
        "report": "+05",
        "tx_mode": "FT4",
        "tx_enabled": True,
        "transmitting": True,
        "decoding": True,
        "rx_df": 0,
        "tx_df": 0xFFFFFFFF,
        "de_call": "YU1ABC/P",
        "de_grid": "KN04ft",
        "dx_grid": "",
        "tx_watchdog": True,
        "sub_mode": "A",
        "fast_mode": True,
        "special_op_mode": 8,
        "frequency_tolerance": 50,
        "tr_period": 7,
        "configuration_name": "IC-7300 FT4",
        "tx_message": "CQ YU1ABC KN04",
    }
    msg = decode(encode_status("WSJT-X", 2**64 - 1, "FT4", None, schema=3, **values))
    assert msg == dict(
        values,
        type="status",
        client="WSJT-X",
        schema=3,
        freq_hz=2**64 - 1,
        mode="FT4",
        dx_call=None,
    )


@pytest.mark.parametrize(
    ("byte", "expected"), [(0x00, False), (0x01, True), (0x02, True), (0xFF, True)]
)
def test_any_non_zero_bool_byte_is_true(byte, expected):
    # QDataStream::operator>>(bool &) reads a qint8 and tests it for non-zero (checked with Qt 6.10)
    packet = encode_status("WSJT-X", 7074000, "FT8", "YU7ABC", report="-12", tx_mode="FT8")
    assert decode(packet + bytes([byte]))["tx_enabled"] is expected


@pytest.mark.parametrize("value", [None, "", "YU7ABC"])
def test_null_and_empty_strings_stay_distinct(value):
    msg = decode(encode_status(value, 7074000, value, value, report=value, sub_mode=value))
    assert msg["client"] == value
    assert msg["mode"] == value
    assert msg["dx_call"] == value
    assert msg["report"] == value
    assert msg["sub_mode"] == value
    heartbeat = decode(encode_heartbeat(value, version=value, revision=value))
    assert (heartbeat["client"], heartbeat["version"], heartbeat["revision"]) == (value,) * 3
    assert decode(encode_logged_adif("WSJT-X", value))["adif"] == value
    assert decode(encode_close(value))["client"] == value


def test_utf8_text_round_trips_with_byte_lengths():
    client = "WSJT-X – Šabac"
    text = "Đorđe Ђорђе čćšžđ ČĆŠŽĐ 73 📻"
    packet = encode_logged_adif(client, text)
    assert decode(packet) == {"type": "logged_adif", "client": client, "schema": 2, "adif": text}
    offset = 12 + 4 + len(client.encode())
    assert struct.unpack_from(">I", packet, offset)[0] == len(text.encode("utf-8"))


def test_text_that_is_not_utf8_is_read_as_latin1():
    # WSJT-X converts the logged ADIF record with QString::toLatin1()
    raw = Writer().header(LOGGED_ADIF, "WSJT-X").byte_array(b"<name:6>J\xfcrgen <EOR>")
    assert decode(raw.getvalue())["adif"] == "<name:6>Jürgen <EOR>"
    packet = Writer().header(CLOSE, None).getvalue()[:-4] + b"\x00\x00\x00\x02\xe9t"
    assert decode(packet)["client"] == "ét"


def test_wsjtx_latin1_record_loses_serbian_letters_before_sending():
    packet = encode_logged_adif("WSJT-X", "<name:5>Đorđe <EOR>", latin1=True)
    assert decode(packet)["adif"] == "<name:5>?or?e <EOR>"  # what a real WSJT-X sends


@pytest.mark.parametrize("schema", [0, 1, 4, 5, 0xFFFFFFFF])
def test_unsupported_schemas_are_ignored(schema):
    packet = Writer().header(HEARTBEAT, "WSJT-X", schema).u32(3).utf8("2.7.0").getvalue()
    assert decode(packet) is None


@pytest.mark.parametrize("code", [2, 3, 5, 13, 99, 0xFFFFFFFF])
def test_unknown_and_unhandled_types_are_other(code):
    packet = Writer().header(code, "WSJT-X").u32(1).utf8("payload").getvalue()
    assert decode(packet) == {"type": "other", "code": code, "client": "WSJT-X", "schema": 2}


def test_realistic_decode_message_is_other():
    # Decode (type 2) as MessageClient::decode writes it
    packet = (
        Writer()
        .header(2, "WSJT-X")
        .boolean(True)
        .u32(67575000)  # QTime: ms since midnight
        .i32(-12)
        .double(0.2)
        .u32(1234)
        .utf8("~")
        .utf8("CQ YU7ABC JN95")
        .boolean(False)
        .boolean(False)
        .getvalue()
    )
    assert decode(packet) == {"type": "other", "code": 2, "client": "WSJT-X", "schema": 2}


def test_jtdx_status_fixture_is_what_the_jtdx_code_writes():
    assert jtdx_status_packet() == fixture("status_jtdx.bin")


# JTDX's id is QApplication::applicationName(): "JTDX", plus " - <rig>" and/or " - test"
@pytest.mark.parametrize("client", ["JTDX", "JTDX - IC7300", "JTDX - test", "JTDX - FT991 - test"])
@pytest.mark.parametrize("tx_first", [True, False])
def test_jtdx_status_has_tx_first_and_no_special_op_mode(client, tx_first):
    # special_op_mode 1 would mean "NA VHF"; the last byte JTDX sends is tx_first
    msg = decode(jtdx_status_packet(client, tx_first))
    assert msg == dict(STATUS_JTDX, client=client, tx_first=tx_first)
    assert list(msg) == STATUS_MANDATORY + JTDX_STATUS_OPTIONAL
    assert "special_op_mode" not in msg


@pytest.mark.parametrize("client", ["WSJT-X", "WSJT-X - JTDX", "MSHV", "jtdx", "", None])
def test_other_client_ids_use_the_wsjtx_status_layout(client):
    header = len(Writer().header(STATUS, "JTDX").getvalue())
    packet = Writer().header(STATUS, client).getvalue() + jtdx_status_packet()[header:]
    msg = decode(packet)
    assert list(msg) == STATUS_MANDATORY + STATUS_OPTIONAL[:14]
    assert msg["special_op_mode"] == 1  # the same byte, read with the WSJT-X layout
    assert "tx_first" not in msg


def test_bytes_after_jtdx_tx_first_are_ignored():
    # a WSJT-X-style tail (tolerance, T/R period, ...) after tx_first is not read
    tail = Writer().u32(0xFFFFFFFF).u32(0xFFFFFFFF).utf8("Default").utf8("CQ").getvalue()
    assert decode(jtdx_status_packet() + tail) == STATUS_JTDX


# --- robustness: truncation, trailing bytes, garbage -------------------------------------------


@pytest.mark.parametrize("name", sorted(ALL_EXPECTED))
def test_every_prefix_of_every_fixture_is_safe(name):
    data = fixture(name)
    for n in range(len(data) + 1):
        check_message(decode(data[:n]))


@pytest.mark.parametrize(
    ("name", "status", "optional"),
    [
        ("status_ft8.bin", STATUS_FT8, STATUS_OPTIONAL),
        ("status_jtdx.bin", STATUS_JTDX, JTDX_STATUS_OPTIONAL),
    ],
)
def test_status_prefixes_keep_whole_fields_only(name, status, optional):
    data = fixture(name)
    mandatory = (status["client"], status["freq_hz"], status["mode"], status["dx_call"])
    ends = []
    for count in range(len(optional) + 1):
        packet = encode_status(*mandatory, **{key: status[key] for key in optional[:count]})
        assert data.startswith(packet)
        ends.append(len(packet))
    assert ends[-1] == len(data)
    for n in range(len(data) + 1):
        whole = [end for end in ends if end <= n]
        if not whole:
            expected = None
        else:
            keys = STATUS_MANDATORY + optional[: len(whole) - 1]
            expected = {key: status[key] for key in keys}
        assert decode(data[:n]) == expected, n


def test_heartbeat_prefixes_need_version_but_not_revision():
    data = fixture("heartbeat_schema3.bin")
    version_end = len(Writer().header(HEARTBEAT, "WSJT-X", 3).u32(3).utf8("2.7.0").getvalue())
    for n in range(len(data) + 1):
        msg = decode(data[:n])
        if n < version_end:
            assert msg is None, n
        elif n < len(data):
            assert msg == dict(EXPECTED["heartbeat_schema3.bin"], revision=None), n
        else:
            assert msg == EXPECTED["heartbeat_schema3.bin"]


@pytest.mark.parametrize("name", ["close.bin", "logged_adif.bin"])
def test_packets_ending_in_a_mandatory_field_need_every_byte(name):
    data = fixture(name)
    for n in range(len(data)):
        assert decode(data[:n]) is None, n
    assert decode(data) == EXPECTED[name]


def test_other_needs_only_the_header():
    data = fixture("qso_logged.bin")
    header = len(Writer().header(QSO_LOGGED, "WSJT-X").getvalue())
    for n in range(len(data) + 1):
        assert decode(data[:n]) == (EXPECTED["qso_logged.bin"] if n >= header else None), n


# Not heartbeat_jtdx.bin: bytes after a JTDX heartbeat are read as the revision field
@pytest.mark.parametrize(
    "name", sorted(set(ENCODED) - {"heartbeat_jtdx.bin"}) + sorted(CAPTURED_EXPECTED)
)
def test_trailing_bytes_are_ignored(name):
    data = fixture(name)
    for tail in (b"\x00", b"\xff" * 5, b"\x00\x00\x00\x03new fields"):
        assert decode(data + tail) == ALL_EXPECTED[name]


def test_huge_declared_lengths_return_none_fast_without_allocating():
    packets = [
        bytes.fromhex("adbccbda 00000002 00000000 fffffffe") + b"WSJT-X",  # id: ~4 GiB
        Writer().header(LOGGED_ADIF, "WSJT-X").u32(0xFFFFFFF0).getvalue() + b"<call:6>",
        Writer().header(STATUS, "WSJT-X").u64(7074000).u32(0x7FFFFFFF).getvalue() + b"FT8",
        Writer().header(HEARTBEAT, "WSJT-X").u32(3).u32(0xFFFFFFFE).getvalue() + b"2.7.0",
    ]
    tracemalloc.start()
    try:
        start = time.perf_counter()
        results = [decode(packet) for packet in packets]
        elapsed = time.perf_counter() - start
        peak = tracemalloc.get_traced_memory()[1]
    finally:
        tracemalloc.stop()
    assert results == [None] * len(packets)
    assert peak < 256 * 1024
    assert elapsed < 0.5


def test_huge_length_in_an_optional_status_field_keeps_what_was_read():
    packet = encode_status("WSJT-X", 7074000, "FT8", "YU7ABC", report="-12")
    packet += struct.pack(">I", 0xFFFFFFF0) + b"FT8"  # tx_mode claims ~4 GiB
    assert decode(packet) == {key: STATUS_FT8[key] for key in STATUS_MANDATORY + ["report"]}


def test_huge_length_in_the_heartbeat_revision_is_treated_as_missing():
    packet = Writer().header(HEARTBEAT, "WSJT-X").u32(3).utf8("2.7.0").u32(0xFFFFFFF0).getvalue()
    assert decode(packet) == dict(EXPECTED["heartbeat_schema2.bin"], revision=None)


@pytest.mark.parametrize(
    "data",
    [
        b"",
        b"\xad\xbc\xcb",
        bytes.fromhex("adbccbda"),
        bytes.fromhex("adbccbda 00000002"),
        bytes.fromhex("adbccbda 00000002 00000000"),
        bytes.fromhex("adbccbda 00000002 00000000 000000"),
        bytes.fromhex("adbccbda 00000002 00000000 00000006") + b"WSJT",
        bytes.fromhex("dacbbcad 02000000 00000000"),
        b"\x00" * 64,
        b"\xff" * 64,
        b"<adif_ver:5>3.1.0<EOH><call:6>YU7ABC<EOR>",  # ADIF text without the UDP framing
    ],
)
def test_short_or_foreign_data_returns_none(data):
    assert decode(data) is None


@pytest.mark.parametrize("data", [None, "adbccbda", 12, 10**12, [0xAD, 0xBC], object()])
def test_non_bytes_input_returns_none(data):
    assert decode(data) is None


def test_bytes_like_input_is_accepted():
    data = fixture("status_ft8.bin")
    assert decode(bytearray(data)) == STATUS_FT8
    assert decode(memoryview(data)) == STATUS_FT8


def test_released_memoryview_returns_none():
    view = memoryview(fixture("status_ft8.bin"))
    view.release()
    assert decode(view) is None


def test_bytes_subclasses_are_read_through_the_buffer_protocol():
    class Odd(bytes):  # decode() reads the buffer, never methods a subclass overrides
        def __bytes__(self) -> bytes:
            raise RuntimeError("__bytes__ called")

        def __len__(self) -> int:
            raise RuntimeError("__len__ called")

        def __getitem__(self, index: object) -> bytes:
            raise RuntimeError("__getitem__ called")

    assert decode(Odd(fixture("status_ft8.bin"))) == STATUS_FT8


def test_ten_thousand_random_byte_strings_never_raise():
    rng = random.Random(20260929)
    for _ in range(10_000):
        check_message(decode(rng.randbytes(rng.randrange(0, 160))))


def random_fields(rng: random.Random) -> bytes:
    """A random sequence of well-formed QDataStream fields (lengths mostly plausible)."""
    writer = Writer()
    for _ in range(rng.randrange(0, 24)):
        kind = rng.randrange(6)
        if kind == 0:
            writer.u8(rng.randrange(256))
        elif kind == 1:
            writer.u32(rng.choice([0, 1, 1500, 0xFFFFFFFF, rng.randrange(2**32)]))
        elif kind == 2:
            writer.u64(rng.randrange(2**64))
        elif kind == 3:
            writer.byte_array(rng.randbytes(rng.randrange(12)))
        elif kind == 4:
            writer.utf8(rng.choice(["", "FT8", "YU7ABC", "Đorđe", "KN04ft"]))
        else:
            writer.utf8(None)
    return writer.getvalue()


def test_random_payloads_behind_a_valid_header_never_raise():
    rng = random.Random(2237)
    seen = dict.fromkeys(["heartbeat", "status", "close", "logged_adif", "other"], 0)
    for _ in range(10_000):
        code = rng.choice([HEARTBEAT, STATUS, CLOSE, LOGGED_ADIF, QSO_LOGGED, rng.randrange(2**32)])
        client = rng.choice(["WSJT-X", "JTDX", "", None])
        packet = Writer().header(code, client, rng.choice([2, 3])).getvalue() + random_fields(rng)
        if rng.random() < 0.3:
            packet = packet[: rng.randrange(len(packet) + 1)]
        msg = decode(packet)
        check_message(msg)
        if msg is not None:
            seen[msg["type"]] += 1
    assert min(seen.values()) >= 100, seen  # the fuzzing reaches every message decoder


def test_corrupting_any_byte_of_any_fixture_never_raises():
    rng = random.Random(12)
    for name in sorted(ALL_EXPECTED):
        data = fixture(name)
        for index in range(len(data)):
            for value in (0x00, 0xFF, data[index] ^ 0x80, rng.randrange(256)):
                corrupted = data[:index] + bytes([value]) + data[index + 1 :]
                check_message(decode(corrupted))


# --- module rules and the fixture generator ----------------------------------------------------


def test_core_module_imports_only_the_standard_library():
    tree = ast.parse(MODULE.read_text(encoding="utf-8"))
    imported = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            imported.add((node.module or "").split(".")[0])
    assert imported <= {"__future__", "struct", "datetime", "typing"}


def run_script(*args: str, env: dict[str, str] | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
        timeout=120,
        env=env,
    )


def test_committed_fixtures_and_readme_are_up_to_date():
    result = run_script("--check")
    assert result.returncode == 0, result.stdout + result.stderr


def test_generator_is_reproducible_and_check_detects_drift(tmp_path):
    result = run_script("--out", str(tmp_path))
    assert result.returncode == 0, result.stdout + result.stderr
    written = sorted(p.name for p in tmp_path.iterdir())
    assert "README.md" in written
    assert set(written) <= {p.name for p in FIXTURES.iterdir()}
    for name in written:
        assert (tmp_path / name).read_bytes() == (FIXTURES / name).read_bytes(), name
    (tmp_path / "close.bin").write_bytes(b"changed")
    result = run_script("--check", "--out", str(tmp_path))
    assert result.returncode == 1
    assert "close.bin" in result.stdout + result.stderr


def test_check_reports_the_files_apart_from_a_failed_qt_check(tmp_path):
    # a qgis package that cannot be imported, found before any real one on sys.path
    (tmp_path / "qgis").mkdir()
    (tmp_path / "qgis" / "__init__.py").write_text("raise ImportError('no Qt here')\n")
    env = dict(os.environ, PYTHONPATH=str(tmp_path), PYTHONDONTWRITEBYTECODE="1")
    result = run_script("--check", "--verify-qt", env=env)
    assert result.returncode == 1  # the Qt check did not run
    assert "--verify-qt needs qgis.PyQt" in result.stderr
    assert "fixtures up to date" in result.stdout  # every committed file matches
    assert "out of date" not in result.stdout
