#!/usr/bin/env python3
"""Generate the fictional demo log ``docs/demo/demo_log.adi`` (README screenshots, trying HamQ).

The log has 150 QSOs of the fictional station YU1ZZZ in KN04ft (Beograd), January to
September 2026, with stations on six continents. Every callsign and QSO is made up: the
callsigns are a real prefix of the entity (and of the call area, where it matters) plus
random letters, so they look plausible but may match a real callsign by chance. The
locators are those of real cities of the entity; bands, modes, times and signal reports
follow the usual propagation (6 m sporadic E in early summer, 160 m and 80 m at night, the
Americas in the European afternoon and evening, Japan and Oceania in the morning, ...).

Each record has what a desktop logger exports after its lookups: ``CALL``, ``GRIDSQUARE``,
``MODE`` (FT4 as ``MFSK`` / ``FT4``), ``RST_SENT`` / ``RST_RCVD``, date and time on and off,
``BAND``, ``FREQ``, ``STATION_CALLSIGN``, ``MY_GRIDSQUARE`` and the DXCC data ``COUNTRY``,
``DXCC``, ``CONT``, ``CQZ``, ``ITUZ``. ADIF DXCC codes, continents and zones are those of
the AD1C country files (cty.dat / cty.csv) for each callsign, and the entity names those
HamQ shows, so the log gives the same statistics with or without a downloaded cty.dat
(checked against the release of 15 September 2026).

The output is reproducible: the same seed gives the same file. Usage::

    python3 scripts/make_demo_log.py            # writes docs/demo/demo_log.adi
    python3 scripts/make_demo_log.py --check    # exit status 1 when the file is out of date
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import random
import sys
from dataclasses import dataclass

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUTPUT = os.path.join(ROOT, "docs", "demo", "demo_log.adi")
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from hamq.core import maidenhead  # noqa: E402 (needs ROOT on sys.path)
from hamq.core.adif import format_record  # noqa: E402
from hamq.core.geo import distance_km  # noqa: E402

SEED = 2026
STATION_CALL = "YU1ZZZ"
STATION_GRID = "KN04ft"
FIRST_DAY = dt.date(2026, 1, 3)
LAST_DAY = dt.date(2026, 9, 27)
ES_SEASON = (dt.date(2026, 5, 20), dt.date(2026, 7, 31))  # 6 m sporadic E
REPEAT_SHARE = 0.15  # chance that a QSO is with a station of the entity worked before

HEADER = (
    "HamQ demo log: {count} fictional QSOs of {call} in {grid} (Beograd), "
    "January to September 2026.\n"
    "Every callsign and QSO in this file is made up. Prefixes, locators, zones and\n"
    "propagation are plausible; a callsign may match a real one by chance.\n"
    "Generated by scripts/make_demo_log.py (seed {seed}).\n"
)


@dataclass(frozen=True)
class City:
    """A place of stations: name, position, callsign prefixes and zones."""

    name: str
    lat: float
    lon: float
    prefixes: tuple[str, ...]
    cq: int
    itu: int


@dataclass(frozen=True)
class Entity:
    """A DXCC entity of the demo log (name, code and continent as in cty.dat / cty.csv)."""

    country: str
    dxcc: int
    cont: str
    qsos: int  # QSOs with stations of this entity
    hours: tuple[int, int]  # usual UTC hours (start, end; end may be past midnight)
    cities: tuple[City, ...]


def _cities(*rows: tuple[str, float, float, str, int, int]) -> tuple[City, ...]:
    """Cities from rows ``(name, lat, lon, "PFX1 PFX2", cq, itu)``."""
    return tuple(
        City(name, lat, lon, tuple(pfx.split()), cq, itu) for name, lat, lon, pfx, cq, itu in rows
    )


# fmt: off
ENTITIES: tuple[Entity, ...] = (
    # --- Europe (68)
    Entity("Fed. Rep. of Germany", 230, "EU", 7, (5, 22), _cities(
        ("Berlin", 52.52, 13.40, "DL1 DK5 DJ3 DO7", 14, 28),
        ("Hamburg", 53.55, 9.99, "DL2 DK8 DF4", 14, 28),
        ("Munich", 48.14, 11.58, "DL8 DK2 DG6", 14, 28),
        ("Cologne", 50.94, 6.96, "DL5 DF1 DH8", 14, 28),
        ("Dresden", 51.05, 13.74, "DL3 DO1", 14, 28),
    )),
    Entity("Italy", 248, "EU", 5, (5, 22), _cities(
        ("Turin", 45.07, 7.69, "IK1 IZ1", 15, 28),
        ("Milan", 45.46, 9.19, "IK2 IZ2 IW2", 15, 28),
        ("Bologna", 44.49, 11.34, "IK4 IZ4", 15, 28),
        ("Florence", 43.77, 11.25, "IK5 IZ5", 15, 28),
        ("Naples", 40.85, 14.27, "IK8 IZ8", 15, 28),
    )),
    Entity("France", 227, "EU", 4, (5, 22), _cities(
        ("Paris", 48.86, 2.35, "F4 F5 F6", 14, 27),
        ("Lyon", 45.76, 4.84, "F4 F8", 14, 27),
        ("Toulouse", 43.60, 1.44, "F5 F6", 14, 27),
        ("Nantes", 47.22, -1.55, "F4 F1", 14, 27),
    )),
    Entity("England", 223, "EU", 4, (5, 22), _cities(
        ("London", 51.51, -0.13, "G4 M0 G3", 14, 27),
        ("Manchester", 53.48, -2.24, "G0 M0 2E0", 14, 27),
        ("Bristol", 51.45, -2.59, "G4 M1", 14, 27),
    )),
    Entity("Spain", 281, "EU", 3, (5, 22), _cities(
        ("Madrid", 40.42, -3.70, "EA4 EB4", 14, 37),
        ("Barcelona", 41.39, 2.17, "EA3 EB3", 14, 37),
        ("Valencia", 39.47, -0.38, "EA5", 14, 37),
        ("Seville", 37.39, -5.98, "EA7", 14, 37),
    )),
    Entity("Poland", 269, "EU", 3, (5, 22), _cities(
        ("Warsaw", 52.23, 21.01, "SP5 SQ5", 15, 28),
        ("Krakow", 50.06, 19.94, "SP9 SQ9", 15, 28),
        ("Gdansk", 54.35, 18.65, "SP2 SQ2", 15, 28),
    )),
    Entity("Czech Republic", 503, "EU", 2, (5, 22), _cities(
        ("Prague", 50.08, 14.44, "OK1", 15, 28),
        ("Brno", 49.20, 16.61, "OK2", 15, 28),
    )),
    Entity("Slovak Republic", 504, "EU", 2, (5, 22), _cities(
        ("Bratislava", 48.15, 17.11, "OM3", 15, 28),
        ("Kosice", 48.72, 21.26, "OM8", 15, 28),
    )),
    Entity("Hungary", 239, "EU", 2, (5, 22), _cities(
        ("Budapest", 47.50, 19.04, "HA5 HG5", 15, 28),
        ("Debrecen", 47.53, 21.63, "HA6 HA8", 15, 28),
    )),
    Entity("Romania", 275, "EU", 2, (5, 22), _cities(
        ("Bucharest", 44.43, 26.10, "YO3", 20, 28),
        ("Cluj-Napoca", 46.77, 23.60, "YO5", 20, 28),
        ("Timisoara", 45.75, 21.23, "YO2", 20, 28),
    )),
    Entity("Bulgaria", 212, "EU", 2, (5, 22), _cities(
        ("Sofia", 42.70, 23.32, "LZ1", 20, 28),
        ("Varna", 43.21, 27.91, "LZ2", 20, 28),
    )),
    Entity("Greece", 236, "EU", 2, (5, 22), _cities(
        ("Athens", 37.98, 23.73, "SV1", 20, 28),
        ("Thessaloniki", 40.64, 22.94, "SV2", 20, 28),
    )),
    Entity("Croatia", 497, "EU", 3, (5, 22), _cities(
        ("Zagreb", 45.81, 15.98, "9A2 9A3", 15, 28),
        ("Split", 43.51, 16.44, "9A5 9A4", 15, 28),
        ("Osijek", 45.55, 18.69, "9A7", 15, 28),
    )),
    Entity("Slovenia", 499, "EU", 2, (5, 22), _cities(
        ("Ljubljana", 46.06, 14.51, "S51 S57", 15, 28),
        ("Maribor", 46.55, 15.65, "S52 S53", 15, 28),
    )),
    Entity("Bosnia-Herzegovina", 501, "EU", 2, (5, 22), _cities(
        ("Sarajevo", 43.86, 18.41, "E71 E77", 15, 28),
        ("Banja Luka", 44.77, 17.19, "E73 E74", 15, 28),
    )),
    Entity("North Macedonia", 502, "EU", 1, (5, 22), _cities(
        ("Skopje", 42.00, 21.43, "Z33 Z35", 15, 28),
    )),
    Entity("Montenegro", 514, "EU", 1, (5, 22), _cities(
        ("Podgorica", 42.44, 19.26, "4O3 4O4", 15, 28),
    )),
    Entity("Serbia", 296, "EU", 2, (5, 22), _cities(
        ("Novi Sad", 45.27, 19.83, "YU7 YT7", 15, 28),
        ("Nis", 43.32, 21.90, "YU1 YT1", 15, 28),
    )),
    Entity("Austria", 206, "EU", 2, (5, 22), _cities(
        ("Vienna", 48.21, 16.37, "OE1", 15, 28),
        ("Graz", 47.07, 15.44, "OE6", 15, 28),
        ("Innsbruck", 47.27, 11.40, "OE7", 15, 28),
    )),
    Entity("Switzerland", 287, "EU", 2, (5, 22), _cities(
        ("Zurich", 47.38, 8.54, "HB9", 14, 28),
        ("Bern", 46.95, 7.45, "HB9", 14, 28),
    )),
    Entity("Belgium", 209, "EU", 1, (5, 22), _cities(
        ("Brussels", 50.85, 4.35, "ON4 ON5", 14, 27),
    )),
    Entity("Netherlands", 263, "EU", 2, (5, 22), _cities(
        ("Amsterdam", 52.37, 4.90, "PA3 PD1", 14, 27),
        ("Eindhoven", 51.44, 5.48, "PA0 PE1", 14, 27),
    )),
    Entity("Denmark", 221, "EU", 1, (5, 22), _cities(
        ("Copenhagen", 55.68, 12.57, "OZ1 OZ5", 14, 18),
    )),
    Entity("Sweden", 284, "EU", 1, (5, 22), _cities(
        ("Stockholm", 59.33, 18.07, "SM0", 14, 18),
        ("Gothenburg", 57.71, 11.97, "SM6", 14, 18),
    )),
    Entity("Norway", 266, "EU", 1, (5, 22), _cities(
        ("Oslo", 59.91, 10.75, "LA2 LA3", 14, 18),
    )),
    Entity("Finland", 224, "EU", 1, (5, 22), _cities(
        ("Helsinki", 60.17, 24.94, "OH2", 15, 18),
    )),
    Entity("Lithuania", 146, "EU", 1, (5, 22), _cities(
        ("Vilnius", 54.69, 25.28, "LY2 LY3", 15, 29),
    )),
    Entity("Ukraine", 288, "EU", 2, (5, 22), _cities(
        ("Kyiv", 50.45, 30.52, "UR5 UT1", 16, 29),
        ("Lviv", 49.84, 24.03, "UR4 UX1", 16, 29),
        ("Odesa", 46.48, 30.72, "UT7 US1", 16, 29),
    )),
    Entity("European Russia", 54, "EU", 2, (5, 22), _cities(
        ("Moscow", 55.76, 37.62, "UA3A RA3A RW3A", 16, 29),
        ("Saint Petersburg", 59.93, 30.34, "UA1A RA1A", 16, 29),
    )),
    Entity("Portugal", 272, "EU", 1, (6, 22), _cities(
        ("Lisbon", 38.72, -9.14, "CT1 CT2", 14, 37),
        ("Porto", 41.15, -8.61, "CT1 CT7", 14, 37),
    )),
    Entity("Ireland", 245, "EU", 1, (6, 22), _cities(
        ("Dublin", 53.35, -6.26, "EI2 EI4", 14, 27),
    )),
    Entity("Scotland", 279, "EU", 1, (6, 22), _cities(
        ("Edinburgh", 55.95, -3.19, "GM4 MM0", 14, 27),
    )),
    # --- Asia (22)
    Entity("Japan", 339, "AS", 6, (4, 11), _cities(
        ("Tokyo", 35.68, 139.69, "JA1 JH1 JR1 JE1", 25, 45),
        ("Osaka", 34.69, 135.50, "JA3 JR3 JH3", 25, 45),
        ("Fukuoka", 33.59, 130.40, "JA6 JH6", 25, 45),
        ("Sapporo", 43.06, 141.35, "JA8 JE8", 25, 45),
    )),
    Entity("China", 318, "AS", 2, (4, 11), _cities(
        ("Beijing", 39.90, 116.40, "BD1 BG1", 24, 44),
        ("Guangzhou", 23.13, 113.26, "BD7I BG7J BH7K", 24, 44),  # 7 + I..P: Guangdong
    )),
    Entity("Republic of Korea", 137, "AS", 1, (4, 11), _cities(
        ("Seoul", 37.57, 126.98, "HL1 DS1", 25, 44),
    )),
    Entity("India", 324, "AS", 2, (5, 16), _cities(
        ("Bengaluru", 12.97, 77.59, "VU2", 22, 41),
        ("Mumbai", 19.08, 72.88, "VU2", 22, 41),
    )),
    Entity("Israel", 336, "AS", 1, (5, 20), _cities(
        ("Tel Aviv", 32.09, 34.78, "4X1 4X4 4Z5", 20, 39),
    )),
    Entity("United Arab Emirates", 391, "AS", 1, (5, 20), _cities(
        ("Dubai", 25.20, 55.27, "A61 A65", 21, 39),
    )),
    Entity("Asiatic Russia", 15, "AS", 3, (2, 16), _cities(
        ("Novosibirsk", 55.01, 82.93, "UA9O RA9O RW9O", 18, 31),
        ("Krasnoyarsk", 56.01, 92.85, "UA0A RA0A", 18, 32),
        ("Vladivostok", 43.12, 131.89, "UA0L RA0L", 19, 34),
    )),
    Entity("Turkey", 390, "AS", 2, (5, 20), _cities(  # cty.dat: "Asiatic Turkey"
        ("Ankara", 39.93, 32.86, "TA2", 20, 39),
        ("Izmir", 38.42, 27.14, "TA3", 20, 39),
    )),
    Entity("Kazakhstan", 130, "AS", 1, (3, 16), _cities(
        ("Almaty", 43.24, 76.89, "UN7 UN9", 17, 30),
    )),
    Entity("Thailand", 387, "AS", 1, (5, 15), _cities(
        ("Bangkok", 13.76, 100.50, "HS0 HS1", 26, 49),
    )),
    Entity("Taiwan", 386, "AS", 1, (4, 11), _cities(
        ("Taipei", 25.03, 121.57, "BV2 BX2", 24, 44),
    )),
    Entity("Singapore", 381, "AS", 1, (5, 15), _cities(
        ("Singapore", 1.35, 103.82, "9V1", 28, 54),
    )),
    # --- Africa (13)
    Entity("South Africa", 462, "AF", 3, (6, 21), _cities(
        ("Johannesburg", -26.20, 28.05, "ZS6 ZS6", 38, 57),
        ("Cape Town", -33.92, 18.42, "ZS1", 38, 57),
        ("Durban", -29.86, 31.03, "ZS5", 38, 57),
    )),
    Entity("Morocco", 446, "AF", 2, (6, 22), _cities(
        ("Casablanca", 33.57, -7.59, "CN8", 33, 37),
        ("Rabat", 34.02, -6.84, "CN8 CN2", 33, 37),
    )),
    Entity("Egypt", 478, "AF", 1, (6, 20), _cities(
        ("Cairo", 30.04, 31.24, "SU1", 34, 38),
    )),
    Entity("Kenya", 430, "AF", 1, (6, 20), _cities(
        ("Nairobi", -1.29, 36.82, "5Z4", 37, 48),
    )),
    Entity("Canary Islands", 29, "AF", 2, (7, 22), _cities(
        ("Las Palmas", 28.12, -15.43, "EA8 EC8", 33, 36),
        ("Santa Cruz de Tenerife", 28.46, -16.25, "EA8", 33, 36),
    )),
    Entity("Nigeria", 450, "AF", 1, (8, 21), _cities(
        ("Lagos", 6.52, 3.38, "5N7 5N0", 35, 46),
    )),
    Entity("Algeria", 400, "AF", 1, (6, 21), _cities(
        ("Algiers", 36.75, 3.06, "7X2 7X5", 33, 37),
    )),
    Entity("Namibia", 464, "AF", 1, (6, 21), _cities(
        ("Windhoek", -22.56, 17.08, "V51 V55", 38, 57),
    )),
    Entity("Mauritius", 165, "AF", 1, (5, 18), _cities(
        ("Port Louis", -20.16, 57.50, "3B8", 39, 53),
    )),
    # --- North America (22)
    Entity("United States", 291, "NA", 15, (12, 25), _cities(
        ("Boston", 42.36, -71.06, "W1 K1 N1 KB1 AA1", 5, 8),
        ("New York", 40.71, -74.01, "W2 K2 N2 KD2", 5, 8),
        ("Philadelphia", 39.95, -75.17, "W3 K3 N3", 5, 8),
        ("Atlanta", 33.75, -84.39, "W4 K4 N4 KI4", 5, 8),
        ("Miami", 25.76, -80.19, "W4 K4 AD4", 5, 8),
        ("Dallas", 32.78, -96.80, "W5 K5 N5 KF5", 4, 7),
        ("San Francisco", 37.77, -122.42, "W6 K6 N6 KJ6", 3, 6),
        ("Los Angeles", 34.05, -118.24, "W6 K6 AI6", 3, 6),
        ("Seattle", 47.61, -122.33, "W7 K7 N7 KG7", 3, 6),
        ("Detroit", 42.33, -83.05, "W8 K8 N8 KD8", 4, 8),
        ("Chicago", 41.88, -87.63, "W9 K9 N9", 4, 8),
        ("Denver", 39.74, -104.99, "W0 K0 N0 KC0", 4, 7),
    )),
    Entity("Canada", 1, "NA", 4, (12, 25), _cities(
        ("Toronto", 43.65, -79.38, "VE3 VA3", 4, 4),
        ("Montreal", 45.50, -73.57, "VE2 VA2", 5, 4),
        ("Vancouver", 49.28, -123.12, "VE7 VA7", 3, 2),
        ("Halifax", 44.65, -63.58, "VE1", 5, 9),
    )),
    Entity("Mexico", 50, "NA", 1, (13, 26), _cities(
        ("Mexico City", 19.43, -99.13, "XE1", 6, 10),
    )),
    Entity("Puerto Rico", 202, "NA", 1, (12, 25), _cities(
        ("San Juan", 18.47, -66.11, "KP4 WP4", 8, 11),
    )),
    Entity("Alaska", 6, "NA", 1, (15, 22), _cities(
        ("Anchorage", 61.22, -149.90, "KL7 AL7", 1, 1),
    )),
    # --- South America (12)
    Entity("Brazil", 108, "SA", 5, (18, 27), _cities(
        ("Rio de Janeiro", -22.91, -43.17, "PY1 PU1", 11, 15),
        ("Sao Paulo", -23.55, -46.63, "PY2 PU2", 11, 15),
        ("Porto Alegre", -30.03, -51.23, "PY3", 11, 15),
        ("Curitiba", -25.43, -49.27, "PY5", 11, 15),
        ("Recife", -8.05, -34.88, "PY7", 11, 13),
    )),
    Entity("Argentina", 100, "SA", 3, (19, 27), _cities(
        ("Buenos Aires", -34.60, -58.38, "LU1 LU5 LW2", 13, 14),
        ("Cordoba", -31.42, -64.18, "LU3 LU7", 13, 14),
        ("Mendoza", -32.89, -68.83, "LU2 LU9", 13, 14),
    )),
    Entity("Chile", 112, "SA", 1, (20, 27), _cities(
        ("Santiago", -33.45, -70.67, "CE3 CA3", 12, 14),
    )),
    Entity("Uruguay", 144, "SA", 1, (19, 27), _cities(
        ("Montevideo", -34.90, -56.16, "CX2 CX4", 13, 14),
    )),
    Entity("Colombia", 116, "SA", 1, (18, 26), _cities(
        ("Bogota", 4.71, -74.07, "HK3 HJ3", 9, 12),
    )),
    Entity("Venezuela", 148, "SA", 1, (18, 26), _cities(
        ("Caracas", 10.49, -66.88, "YV5", 9, 12),
    )),
    # --- Oceania (13)
    Entity("Australia", 150, "OC", 6, (5, 9), _cities(
        ("Sydney", -33.87, 151.21, "VK2", 30, 59),
        ("Melbourne", -37.81, 144.96, "VK3", 30, 59),
        ("Brisbane", -27.47, 153.03, "VK4", 30, 55),
        ("Adelaide", -34.93, 138.60, "VK5", 30, 59),
        ("Perth", -31.95, 115.86, "VK6", 29, 58),
    )),
    Entity("New Zealand", 170, "OC", 3, (6, 9), _cities(
        ("Auckland", -36.85, 174.76, "ZL1", 32, 60),
        ("Wellington", -41.29, 174.78, "ZL2", 32, 60),
        ("Christchurch", -43.53, 172.64, "ZL3", 32, 60),
    )),
    Entity("Hawaii", 110, "OC", 1, (6, 9), _cities(
        ("Honolulu", 21.31, -157.86, "KH6 AH6", 31, 61),
    )),
    Entity("Indonesia", 327, "OC", 1, (8, 16), _cities(
        ("Jakarta", -6.21, 106.85, "YB0 YC0", 28, 54),
    )),
    Entity("Philippines", 375, "OC", 1, (8, 16), _cities(
        ("Manila", 14.60, 120.98, "DU1 DV1", 27, 50),
    )),
    Entity("New Caledonia", 162, "OC", 1, (6, 9), _cities(
        ("Noumea", -22.27, 166.44, "FK8", 32, 56),
    )),
)
# fmt: on

#: Bands by distance (km): (upper limit, ((band, weight), ...)).
BANDS_BY_DISTANCE = (
    (800, (("80m", 4), ("40m", 4), ("160m", 1), ("30m", 1))),
    (3000, (("40m", 4), ("20m", 4), ("30m", 2), ("80m", 2), ("17m", 1), ("15m", 1), ("6m", 2))),
    (8000, (("20m", 6), ("17m", 3), ("15m", 3), ("40m", 2), ("30m", 2), ("12m", 1), ("10m", 2))),
    (99999, (("20m", 6), ("15m", 3), ("17m", 3), ("10m", 3), ("12m", 1), ("40m", 1), ("30m", 1))),
)
MODES = (("FT8", 55), ("CW", 17), ("SSB", 15), ("FT4", 9), ("RTTY", 4))
# fmt: off
#: Dial frequencies (MHz) of FT8 / FT4 and the CW / SSB / RTTY segments used.
FT8_DIAL = {"160m": 1.840, "80m": 3.573, "40m": 7.074, "30m": 10.136, "20m": 14.074,
            "17m": 18.100, "15m": 21.074, "12m": 24.915, "10m": 28.074, "6m": 50.313}
FT4_DIAL = {"80m": 3.575, "40m": 7.0475, "30m": 10.140, "20m": 14.080, "17m": 18.104,
            "15m": 21.140, "12m": 24.919, "10m": 28.180, "6m": 50.318}
SEGMENTS = {
    "CW": {"160m": (1.810, 1.838), "80m": (3.510, 3.560), "40m": (7.005, 7.035),
           "30m": (10.105, 10.125), "20m": (14.010, 14.060), "17m": (18.070, 18.090),
           "15m": (21.010, 21.060), "12m": (24.895, 24.912), "10m": (28.010, 28.060),
           "6m": (50.080, 50.098)},
    "SSB": {"80m": (3.650, 3.790), "40m": (7.100, 7.190), "20m": (14.150, 14.340),
            "17m": (18.120, 18.165), "15m": (21.200, 21.420), "12m": (24.940, 24.985),
            "10m": (28.400, 28.700), "6m": (50.120, 50.180)},
    "RTTY": {"80m": (3.580, 3.598), "40m": (7.040, 7.048), "20m": (14.080, 14.095),
             "17m": (18.100, 18.108), "15m": (21.080, 21.100), "10m": (28.080, 28.100)},
}
# fmt: on
NIGHT_BANDS = ("160m", "80m")
NIGHT_HOURS = (18, 29)  # 18 to 05 UTC


@dataclass
class Qso:
    """One generated QSO (the record is built from it)."""

    when: dt.datetime
    call: str
    entity: Entity
    city: City
    band: str
    mode: str
    freq: float
    grid: str
    rst_sent: str
    rst_rcvd: str
    seconds: int  # duration

    def key(self) -> tuple[str, str, str, str]:
        """The duplicate key HamQ uses: call, minute, band and mode."""
        return self.call, self.when.strftime("%Y%m%d%H%M"), self.band, self.mode

    def record(self) -> dict[str, str]:
        """ADIF fields in the order WSJT-X writes them, then the logger's DXCC data."""
        off = self.when + dt.timedelta(seconds=self.seconds)
        mode, submode = ("MFSK", "FT4") if self.mode == "FT4" else (self.mode, None)
        fields: dict[str, str | None] = {
            "CALL": self.call,
            "GRIDSQUARE": self.grid,
            "MODE": mode,
            "SUBMODE": submode,
            "RST_SENT": self.rst_sent,
            "RST_RCVD": self.rst_rcvd,
            "QSO_DATE": self.when.strftime("%Y%m%d"),
            "TIME_ON": self.when.strftime("%H%M%S"),
            "QSO_DATE_OFF": off.strftime("%Y%m%d"),
            "TIME_OFF": off.strftime("%H%M%S"),
            "BAND": self.band,
            "FREQ": f"{self.freq:.6f}",
            "STATION_CALLSIGN": STATION_CALL,
            "MY_GRIDSQUARE": STATION_GRID,
            "COUNTRY": self.entity.country,
            "DXCC": str(self.entity.dxcc),
            "CONT": self.entity.cont,
            "CQZ": str(self.city.cq),
            "ITUZ": str(self.city.itu),
        }
        return {name: value for name, value in fields.items() if value is not None}


def _weighted(rng: random.Random, choices: tuple[tuple[str, int], ...]) -> str:
    names = [name for name, _ in choices]
    weights = [weight for _, weight in choices]
    return rng.choices(names, weights=weights)[0]


def _suffix(rng: random.Random, prefix: str) -> str:
    """Random letters after ``prefix``; never a Q first (Q codes)."""
    letters = "ABCDEFGHIJKLMNOPRSTUVWXYZ"
    if prefix[-1].isalpha():  # region letter (Russia, China) already there: one or two more
        return "".join(rng.choice(letters) for _ in range(rng.choice((1, 2, 2))))
    length = 3 if rng.random() < 0.7 else 2
    return "".join(rng.choice(letters) for _ in range(length))


def _band(rng: random.Random, km: float) -> str:
    for limit, choices in BANDS_BY_DISTANCE:
        if km <= limit:
            return _weighted(rng, choices)
    raise AssertionError(km)


def _mode(rng: random.Random, band: str) -> str:
    while True:
        mode = _weighted(rng, MODES)
        if mode == "SSB" and band in ("30m", "160m"):
            continue  # no telephony on 30 m; 160 m SSB is rare
        if mode == "RTTY" and band not in SEGMENTS["RTTY"]:
            continue
        if mode == "FT4" and band not in FT4_DIAL:
            continue
        return mode


def _frequency(rng: random.Random, band: str, mode: str) -> float:
    if mode in ("FT8", "FT4"):
        dial = (FT8_DIAL if mode == "FT8" else FT4_DIAL)[band]
        return dial + rng.randint(300, 2800) / 1e6  # audio offset
    low, high = SEGMENTS[mode][band]
    return round(rng.uniform(low, high), 4 if mode == "SSB" else 5)


def _reports(rng: random.Random, mode: str) -> tuple[str, str]:
    if mode in ("FT8", "FT4"):
        sent, rcvd = rng.randint(-20, 8), rng.randint(-20, 8)
        return f"{sent:+03d}", f"{rcvd:+03d}"
    if mode == "SSB":
        return rng.choice(("59", "59", "57", "55")), rng.choice(("59", "57", "57", "55"))
    return rng.choice(("599", "599", "579")), rng.choice(("599", "589", "579"))


def _day(rng: random.Random, band: str) -> dt.date:
    first, last = ES_SEASON if band == "6m" else (FIRST_DAY, LAST_DAY)
    return first + dt.timedelta(days=rng.randint(0, (last - first).days))


def _time(rng: random.Random, day: dt.date, hours: tuple[int, int], band: str) -> dt.datetime:
    start, end = NIGHT_HOURS if band in NIGHT_BANDS else hours
    hour = rng.randint(start, end - 1) if end > start else start
    moment = dt.datetime(day.year, day.month, day.day, tzinfo=dt.timezone.utc)
    return moment + dt.timedelta(hours=hour, minutes=rng.randint(0, 59), seconds=rng.randint(0, 59))


def _duration(rng: random.Random, mode: str) -> int:
    if mode in ("FT8", "FT4"):
        return rng.randint(45, 120) if mode == "FT8" else rng.randint(25, 60)
    return rng.randint(40, 240)


def generate(seed: int = SEED) -> list[Qso]:
    """The QSOs of the demo log in time order (the same for the same seed)."""
    rng = random.Random(seed)
    my_lat, my_lon = maidenhead.to_latlon(STATION_GRID)
    qsos: list[Qso] = []
    keys: set[tuple[str, str, str, str]] = set()
    worked: dict[str, list[tuple[str, City]]] = {}  # entity -> calls already worked
    for entity in ENTITIES:
        for _ in range(entity.qsos):
            earlier = worked.get(entity.country, [])
            if earlier and rng.random() < REPEAT_SHARE:
                call, city = rng.choice(earlier)  # the same station again
            else:
                city = rng.choice(entity.cities)
                prefix = rng.choice(city.prefixes)
                call = prefix + _suffix(rng, prefix)
                worked.setdefault(entity.country, []).append((call, city))
            km = distance_km(my_lat, my_lon, city.lat, city.lon)
            while True:
                band = _band(rng, km)
                mode = _mode(rng, band)
                when = _time(rng, _day(rng, band), entity.hours, band)
                qso = Qso(
                    when=when,
                    call=call,
                    entity=entity,
                    city=city,
                    band=band,
                    mode=mode,
                    freq=_frequency(rng, band, mode),
                    # FT8 and FT4 exchange the 4-character square; the logger's lookup
                    # gives 6 characters for the other modes
                    grid=maidenhead.to_locator(
                        city.lat, city.lon, 4 if mode in ("FT8", "FT4") else 6
                    ),
                    rst_sent="",
                    rst_rcvd="",
                    seconds=_duration(rng, mode),
                )
                if qso.key() not in keys:
                    break
            qso.rst_sent, qso.rst_rcvd = _reports(rng, mode)
            keys.add(qso.key())
            qsos.append(qso)
    qsos.sort(key=lambda qso: (qso.when, qso.call))
    return qsos


def document(qsos: list[Qso], seed: int = SEED) -> str:
    """The .adi text: free-text header, header fields, one record per line."""
    header = HEADER.format(count=len(qsos), call=STATION_CALL, grid=STATION_GRID, seed=seed)
    fields = {"ADIF_VER": "3.1.4", "PROGRAMID": "HamQ demo log", "PROGRAMVERSION": "0.1.0"}
    lines = [f"<{name}:{len(value)}>{value}" for name, value in fields.items()]
    return (
        header + "\n".join(lines) + "\n<EOH>\n" + "".join(format_record(q.record()) for q in qsos)
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="the .adi file to write")
    parser.add_argument("--seed", type=int, default=SEED, help="random seed (default %(default)s)")
    parser.add_argument("--check", action="store_true", help="only compare with --output")
    args = parser.parse_args(argv)

    total = sum(entity.qsos for entity in ENTITIES)
    qsos = generate(args.seed)
    if len(qsos) != total:
        print(f"generated {len(qsos)} QSOs instead of {total}", file=sys.stderr)
        return 2
    text = document(qsos, args.seed)
    if args.check:
        try:
            with open(args.output, encoding="utf-8", newline="") as handle:
                current = handle.read()
        except OSError:
            current = ""
        if current != text:
            print(f"out of date: {args.output}", file=sys.stderr)
            return 1
        print(f"up to date: {args.output}")
        return 0
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    continents = sorted({qso.entity.cont for qso in qsos})
    entities = len({qso.entity.dxcc for qso in qsos})
    calls = len({qso.call for qso in qsos})
    print(
        f"wrote {args.output}: {len(qsos)} QSOs, {calls} callsigns, {entities} DXCC entities, "
        f"continents {' '.join(continents)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
